---
name: CI for Foodgram

on:
  push:
    branches: [master]

jobs:
  copy_files_to_server:
    name: Copy infra and docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Create projects directory
        uses: appleboy/ssh-action@v0.1.8
        with:
          # command: cd projects && mkdir -p foodgram && mkdir -p foodgram/docs
          command: cd projects && mkdir -p foodgram && mkdir -p foodgram/docs
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}

      - name: Copy infra files
        uses: appleboy/ssh-action@v0.1.8
        with:
          local: infra/
          remote: /${{ secrets.USERNAME }}/projects/foodgram/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}

      - name: Copy docs
        uses: appleboy/ssh-action@v0.1.8
        with:
          local: docs
          remote: /${{ secrets.USERNAME }}/projects/foodgram/docs/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}

  build_push_backend_to_DockerHub:
    name: Building back image and pushing it to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push "foodgram/backend" to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: backend/
          push: true
          tags: ${{ secrets.DOCKER_USER }}/foodgram_back:latest

  build_push_frontend_to_DockerHub:
    name: Building front image and pushing it to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push "foodgram/frontend" to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: frontend/
          push: true
          tags: ${{ secrets.DOCKER_USER }}/foodgram_front:latest

  deploy:
    runs-on: ubuntu-22.04
    needs:
      - copy_files_to_server
      - build_push_backend_to_DockerHub
      - build_push_frontend_to_DockerHub
    steps:
      - name: remote ssh commands to deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            pwd
            ls -a
            ls -a projects/


